"""
Euler Project 2
============================================================================================================================================
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms
will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
fibonacci_seq = [1, 2]
while fibonacci_seq[-1] < 4000000:
	fibonacci_seq.append(fibonacci_seq[-1] + fibonacci_seq[-2])	

answer = [i for i in fibonacci_seq if i%2 == 0]
print sum(answer)
