"""
Euler Project 2
============================================================================================================================================
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms
will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
total = 0
currVal = 0
Fibonacci_Seq = [1, 2]

while(currVal < 4000000):
    # create the Fib sequence
    currVal = Fibonacci_Seq[-1] + Fibonacci_Seq[-2]
    # append on values to the sequence
    Fibonacci_Seq.append(currVal)
    if(Fibonacci_Seq[-1] > 4000000):
        del(Fibonacci_Seq[-1])        
        
print Fibonacci_Seq

for value in Fibonacci_Seq:
    if(value%2 == 0):
        total = total + value
        
print total
